{% set name = "diffmah" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ArgonneCPAC/diffmah/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 51b7dac196faa4bd87fcdc7708a4b276e9d35a18331f89d91bfa42d0daa8d715

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - jax >=0.3.0

test:
  imports:
    - diffmah

about:
  home: https://github.com/ArgonneCPAC/diffmah
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Differentiable models of halo and galaxy formation history

extra:
  recipe-maintainers:
    - beckermr
