{% set name = "diffmah" %}
{% set version = "0.7.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ArgonneCPAC/diffmah/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 048491a6fbf926fd090ef40e45cac6cf7f1de09f29afc93723c2b757c492dff4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm >=7
  run:
    - python >={{ python_min }}
    - numpy
    - jax >=0.3.0

test:
  imports:
    - diffmah
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/ArgonneCPAC/diffmah
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Differentiable models of halo and galaxy formation history

extra:
  recipe-maintainers:
    - beckermr
