{% set name = "diffmah" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ArgonneCPAC/diffmah/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 96f6b43363157057ba4809c8ae86935f8917461ad1c557391d9def9d23addcf9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm >=7
  run:
    - python >=3.6
    - numpy
    - jax >=0.3.0

test:
  imports:
    - diffmah

about:
  home: https://github.com/ArgonneCPAC/diffmah
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Differentiable models of halo and galaxy formation history

extra:
  recipe-maintainers:
    - beckermr
