{% set name = "diffmah" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ArgonneCPAC/diffmah/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 50ef66d2741dbdbc48d77f41a2fbb08deb42036517928e40125ccd1decf4912f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm >=7
  run:
    - python >=3.6
    - numpy
    - jax >=0.3.0

test:
  imports:
    - diffmah

about:
  home: https://github.com/ArgonneCPAC/diffmah
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Differentiable models of halo and galaxy formation history

extra:
  recipe-maintainers:
    - beckermr
